language: c
dist: bionic

branches:
  only:
    - master

jobs:
  allow_failures:
  - os: osx
    compiler: gcc-9.2

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang
    osx_image: xcode11.3
  - os: osx
    env: INSTALL=gcc
    compiler: gcc-9.2
    osx_image: xcode11.3

before_install:
  - if [ "$TRAVIS_OS_NAME" == osx -a "$INSTALL" ] ; then brew install $INSTALL || true ; fi

script:
  - make
  - make test
